//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""gameplay"",
            ""id"": ""cd06d251-7210-410f-ac5a-c8393199d849"",
            ""actions"": [
                {
                    ""name"": ""attack"",
                    ""type"": ""Button"",
                    ""id"": ""485e2196-6a27-4fe3-a9da-744381a3b499"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""attack1"",
                    ""type"": ""Button"",
                    ""id"": ""e1a057cf-0ba6-4529-a6a9-37fc081a4aaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""special"",
                    ""type"": ""Button"",
                    ""id"": ""d68e06f1-de0b-4f7c-a832-c294661bfc88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""special1"",
                    ""type"": ""Button"",
                    ""id"": ""abe610b9-d504-4c3b-9d8b-df03aa5c1727"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""c6786b4f-9eb3-4cd8-8860-65635bc192b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump1"",
                    ""type"": ""Button"",
                    ""id"": ""1879c890-5cc3-41cc-92eb-c9df4bc030b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""modechange"",
                    ""type"": ""Button"",
                    ""id"": ""57ccf2ce-7b56-4f56-91b5-0598ca879a7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""menu"",
                    ""type"": ""Button"",
                    ""id"": ""458931c4-6396-4945-97c4-c38b0e893ae3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""down"",
                    ""type"": ""Button"",
                    ""id"": ""968db628-9bee-42cf-b020-7cb456054317"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""up"",
                    ""type"": ""Button"",
                    ""id"": ""97f50be6-7b2f-4413-a3b1-ef87eb196b5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""up1"",
                    ""type"": ""Button"",
                    ""id"": ""42dd92b1-64d3-4671-9b2e-b957f4ba5f6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""down1"",
                    ""type"": ""Button"",
                    ""id"": ""2e918eae-8cc0-439d-add5-e5be03007c6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveleft"",
                    ""type"": ""Button"",
                    ""id"": ""cadfdfee-d132-4138-8add-30548612a806"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveleft1"",
                    ""type"": ""Button"",
                    ""id"": ""75b409db-c161-446a-bdf1-5904763e6d7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveright"",
                    ""type"": ""Button"",
                    ""id"": ""869e1407-443f-4185-8df4-437f72db3325"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""moveright1"",
                    ""type"": ""Button"",
                    ""id"": ""51a727e1-f8ae-45b0-beb9-199922b13bba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shield"",
                    ""type"": ""Button"",
                    ""id"": ""ec5dbcc9-1b12-4598-828d-17b4e6239215"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shield1"",
                    ""type"": ""Button"",
                    ""id"": ""a937e790-229e-4f72-9074-c1ea45617f9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9481b057-cce6-4c45-9641-8e1f568dd4a3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5265d56-b334-4d43-b384-2c20b5295e8d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c592d03-c0bb-44a0-b4a9-b3611392cbe0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb0ce881-1f03-43ae-8e8e-35b612c4549a"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdf841c6-0067-4b07-ae5c-6410864af63b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""modechange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecace223-fc95-432a-bf87-458c0d52e0e2"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""modechange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eccf714f-20f4-421d-8c58-cedf1ec28476"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca165807-79d3-4dd2-891a-73d0b1e776a7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dc094c2-f9ce-4643-a5f6-85939354bd80"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c7f5b48-6e1b-408e-8987-6523990413fe"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61905332-6cb5-4c20-bdbc-5a8164015603"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveleft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac06e0ef-6f6b-4e41-be9b-fa4d7890f8e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveleft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f5ced3b-0a0e-400a-ad29-d3f53d2b1bec"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveright"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c06cf6ef-6fba-4faa-a823-288b4f055504"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveright"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd63b7fe-c6b4-4a1a-8f6f-323fc2fd7b1c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""attack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cf08d5a-4574-4351-8a94-e46c6c106f2b"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""attack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d21b0055-095e-46cf-9676-4ecfb52efdf9"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""down1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d05b68e-924d-4338-bb0c-ec52e8c5445f"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""down1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7454c667-ef05-43e2-b49a-34801c4d2f1e"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveleft1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""678ea428-8122-4fea-9c76-928033c8221f"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveleft1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef6c9977-4fb2-4b52-a4fa-9c1c4c1fdcaf"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveright1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5e99a9e-1f3e-4a0b-8ca9-a86c15844170"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveright1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72fd765a-e030-41a3-aa08-5181e9f9f918"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf9a3f93-1e81-4fc8-bed5-bd3aeeedac9c"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bc0164d-65ed-407a-b77f-80db08176e62"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8535f87a-1268-41d0-8368-0b792bfee88b"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d13375f8-c88d-47e6-ba0f-5d659f9c0949"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c2ba309-cb7b-42a9-a41b-efe564b492c0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d207c9d-9eb4-4358-a446-94eaab5f22d5"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""up1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7018429c-8949-460b-b717-076f99afc0c5"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""up1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7df3372-70db-43c4-88b7-8eb4df690644"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c829c86-0d14-4dfa-a8d9-2c9b337c3f57"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2610642b-dfb7-4911-9d53-14b71a162728"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35bee264-c23e-437d-ba01-745f1082dcb6"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // gameplay
        m_gameplay = asset.FindActionMap("gameplay", throwIfNotFound: true);
        m_gameplay_attack = m_gameplay.FindAction("attack", throwIfNotFound: true);
        m_gameplay_attack1 = m_gameplay.FindAction("attack1", throwIfNotFound: true);
        m_gameplay_special = m_gameplay.FindAction("special", throwIfNotFound: true);
        m_gameplay_special1 = m_gameplay.FindAction("special1", throwIfNotFound: true);
        m_gameplay_jump = m_gameplay.FindAction("jump", throwIfNotFound: true);
        m_gameplay_jump1 = m_gameplay.FindAction("jump1", throwIfNotFound: true);
        m_gameplay_modechange = m_gameplay.FindAction("modechange", throwIfNotFound: true);
        m_gameplay_menu = m_gameplay.FindAction("menu", throwIfNotFound: true);
        m_gameplay_down = m_gameplay.FindAction("down", throwIfNotFound: true);
        m_gameplay_up = m_gameplay.FindAction("up", throwIfNotFound: true);
        m_gameplay_up1 = m_gameplay.FindAction("up1", throwIfNotFound: true);
        m_gameplay_down1 = m_gameplay.FindAction("down1", throwIfNotFound: true);
        m_gameplay_moveleft = m_gameplay.FindAction("moveleft", throwIfNotFound: true);
        m_gameplay_moveleft1 = m_gameplay.FindAction("moveleft1", throwIfNotFound: true);
        m_gameplay_moveright = m_gameplay.FindAction("moveright", throwIfNotFound: true);
        m_gameplay_moveright1 = m_gameplay.FindAction("moveright1", throwIfNotFound: true);
        m_gameplay_shield = m_gameplay.FindAction("shield", throwIfNotFound: true);
        m_gameplay_shield1 = m_gameplay.FindAction("shield1", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gameplay
    private readonly InputActionMap m_gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_gameplay_attack;
    private readonly InputAction m_gameplay_attack1;
    private readonly InputAction m_gameplay_special;
    private readonly InputAction m_gameplay_special1;
    private readonly InputAction m_gameplay_jump;
    private readonly InputAction m_gameplay_jump1;
    private readonly InputAction m_gameplay_modechange;
    private readonly InputAction m_gameplay_menu;
    private readonly InputAction m_gameplay_down;
    private readonly InputAction m_gameplay_up;
    private readonly InputAction m_gameplay_up1;
    private readonly InputAction m_gameplay_down1;
    private readonly InputAction m_gameplay_moveleft;
    private readonly InputAction m_gameplay_moveleft1;
    private readonly InputAction m_gameplay_moveright;
    private readonly InputAction m_gameplay_moveright1;
    private readonly InputAction m_gameplay_shield;
    private readonly InputAction m_gameplay_shield1;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @attack => m_Wrapper.m_gameplay_attack;
        public InputAction @attack1 => m_Wrapper.m_gameplay_attack1;
        public InputAction @special => m_Wrapper.m_gameplay_special;
        public InputAction @special1 => m_Wrapper.m_gameplay_special1;
        public InputAction @jump => m_Wrapper.m_gameplay_jump;
        public InputAction @jump1 => m_Wrapper.m_gameplay_jump1;
        public InputAction @modechange => m_Wrapper.m_gameplay_modechange;
        public InputAction @menu => m_Wrapper.m_gameplay_menu;
        public InputAction @down => m_Wrapper.m_gameplay_down;
        public InputAction @up => m_Wrapper.m_gameplay_up;
        public InputAction @up1 => m_Wrapper.m_gameplay_up1;
        public InputAction @down1 => m_Wrapper.m_gameplay_down1;
        public InputAction @moveleft => m_Wrapper.m_gameplay_moveleft;
        public InputAction @moveleft1 => m_Wrapper.m_gameplay_moveleft1;
        public InputAction @moveright => m_Wrapper.m_gameplay_moveright;
        public InputAction @moveright1 => m_Wrapper.m_gameplay_moveright1;
        public InputAction @shield => m_Wrapper.m_gameplay_shield;
        public InputAction @shield1 => m_Wrapper.m_gameplay_shield1;
        public InputActionMap Get() { return m_Wrapper.m_gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @attack.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @attack.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @attack.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @attack1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack1;
                @attack1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack1;
                @attack1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack1;
                @special.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecial;
                @special.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecial;
                @special.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecial;
                @special1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecial1;
                @special1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecial1;
                @special1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSpecial1;
                @jump.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @jump.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @jump.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @jump1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump1;
                @jump1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump1;
                @jump1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump1;
                @modechange.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnModechange;
                @modechange.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnModechange;
                @modechange.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnModechange;
                @menu.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMenu;
                @menu.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMenu;
                @menu.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMenu;
                @down.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDown;
                @down.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDown;
                @down.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDown;
                @up.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUp;
                @up.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUp;
                @up.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUp;
                @up1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUp1;
                @up1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUp1;
                @up1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUp1;
                @down1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDown1;
                @down1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDown1;
                @down1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDown1;
                @moveleft.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveleft;
                @moveleft.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveleft;
                @moveleft.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveleft;
                @moveleft1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveleft1;
                @moveleft1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveleft1;
                @moveleft1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveleft1;
                @moveright.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveright;
                @moveright.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveright;
                @moveright.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveright;
                @moveright1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveright1;
                @moveright1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveright1;
                @moveright1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMoveright1;
                @shield.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShield;
                @shield.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShield;
                @shield.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShield;
                @shield1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShield1;
                @shield1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShield1;
                @shield1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShield1;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @attack.started += instance.OnAttack;
                @attack.performed += instance.OnAttack;
                @attack.canceled += instance.OnAttack;
                @attack1.started += instance.OnAttack1;
                @attack1.performed += instance.OnAttack1;
                @attack1.canceled += instance.OnAttack1;
                @special.started += instance.OnSpecial;
                @special.performed += instance.OnSpecial;
                @special.canceled += instance.OnSpecial;
                @special1.started += instance.OnSpecial1;
                @special1.performed += instance.OnSpecial1;
                @special1.canceled += instance.OnSpecial1;
                @jump.started += instance.OnJump;
                @jump.performed += instance.OnJump;
                @jump.canceled += instance.OnJump;
                @jump1.started += instance.OnJump1;
                @jump1.performed += instance.OnJump1;
                @jump1.canceled += instance.OnJump1;
                @modechange.started += instance.OnModechange;
                @modechange.performed += instance.OnModechange;
                @modechange.canceled += instance.OnModechange;
                @menu.started += instance.OnMenu;
                @menu.performed += instance.OnMenu;
                @menu.canceled += instance.OnMenu;
                @down.started += instance.OnDown;
                @down.performed += instance.OnDown;
                @down.canceled += instance.OnDown;
                @up.started += instance.OnUp;
                @up.performed += instance.OnUp;
                @up.canceled += instance.OnUp;
                @up1.started += instance.OnUp1;
                @up1.performed += instance.OnUp1;
                @up1.canceled += instance.OnUp1;
                @down1.started += instance.OnDown1;
                @down1.performed += instance.OnDown1;
                @down1.canceled += instance.OnDown1;
                @moveleft.started += instance.OnMoveleft;
                @moveleft.performed += instance.OnMoveleft;
                @moveleft.canceled += instance.OnMoveleft;
                @moveleft1.started += instance.OnMoveleft1;
                @moveleft1.performed += instance.OnMoveleft1;
                @moveleft1.canceled += instance.OnMoveleft1;
                @moveright.started += instance.OnMoveright;
                @moveright.performed += instance.OnMoveright;
                @moveright.canceled += instance.OnMoveright;
                @moveright1.started += instance.OnMoveright1;
                @moveright1.performed += instance.OnMoveright1;
                @moveright1.canceled += instance.OnMoveright1;
                @shield.started += instance.OnShield;
                @shield.performed += instance.OnShield;
                @shield.canceled += instance.OnShield;
                @shield1.started += instance.OnShield1;
                @shield1.performed += instance.OnShield1;
                @shield1.canceled += instance.OnShield1;
            }
        }
    }
    public GameplayActions @gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnAttack(InputAction.CallbackContext context);
        void OnAttack1(InputAction.CallbackContext context);
        void OnSpecial(InputAction.CallbackContext context);
        void OnSpecial1(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnJump1(InputAction.CallbackContext context);
        void OnModechange(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnUp1(InputAction.CallbackContext context);
        void OnDown1(InputAction.CallbackContext context);
        void OnMoveleft(InputAction.CallbackContext context);
        void OnMoveleft1(InputAction.CallbackContext context);
        void OnMoveright(InputAction.CallbackContext context);
        void OnMoveright1(InputAction.CallbackContext context);
        void OnShield(InputAction.CallbackContext context);
        void OnShield1(InputAction.CallbackContext context);
    }
}
